        <footer class="bg-primary">
            <div class="text-center">by frigidor and kindly supported by BlaiNnnn
                See <a href="https://github.com/pascalbuehler/gc-tourfinder" target="_blank">GitHub</a>
            </div>
        </footer>

        <script src="/vendor/jquery/dist/jquery.min.js"></script>
        <script src="/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="/vendor/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="/vendor/bootstrap-datepicker/dist/locales/bootstrap-datepicker.de.min.js"></script>
        <script src="/vendor/bootstrap-validator/dist/validator.min.js"></script>
        <script src="/assets/js/main.js"></script>
    </body>
</html>