        <footer class="bg-primary">
            <div class="text-center">by frigidor and kindly supported by BlaiNnnn
                See <a href="https://github.com/pascalbuehler/gc-tourfinder" target="_blank">GitHub</a>
            </div>
        </footer>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="/assets/js/main.js"></script>
    </body>
</html>