<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>GC Tourfinder</title>

        <link href="<?= $config['baseUrl'] ?>/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?= $config['baseUrl'] ?>/vendor/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css" rel="stylesheet">
        <link href="<?= $config['baseUrl'] ?>/assets/css/style.css" rel="stylesheet">

        <!--[if lt IE 9]>
        <script src="<?= $config['baseUrl'] ?>/vendor/html5shiv/dist/html5shiv.min.js"></script>
        <script src="<?= $config['baseUrl'] ?>/vendor/respond/dest/respond.min.js"></script>
        <![endif]-->
        
        <link rel="apple-touch-icon" sizes="57x57" href="<?= $config['baseUrl'] ?>/assets/icons/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="<?= $config['baseUrl'] ?>/assets/icons/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="<?= $config['baseUrl'] ?>/assets/icons/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="<?= $config['baseUrl'] ?>/assets/icons/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="<?= $config['baseUrl'] ?>/assets/icons/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="<?= $config['baseUrl'] ?>/assets/icons/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="<?= $config['baseUrl'] ?>/assets/icons/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="<?= $config['baseUrl'] ?>/assets/icons/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="<?= $config['baseUrl'] ?>/assets/icons/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="<?= $config['baseUrl'] ?>/assets/icons/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="<?= $config['baseUrl'] ?>/assets/icons/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="<?= $config['baseUrl'] ?>/assets/icons/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="<?= $config['baseUrl'] ?>/assets/icons/favicon-16x16.png">
        <link rel="manifest" href="<?= $config['baseUrl'] ?>/assets/icons/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="<?= $config['baseUrl'] ?>/assets/icons/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">
    </head>
    <body>
        <header class="bg-primary">
            <h1 class="nomargin-top text-center"><img id="icon" src="<?= $config['baseUrl'] ?>/assets/icons/favicon-32x32.png" width="32" height="32" alt="GC Tourfinder"> <a href="/">GC Tourfinder</a></h1>
        </header>