<?php include('partials/header.phtml'); ?>

    <div class="container">
        <div class="row">
            <form data-toggle="validator" action="/usertours" role="form">
                <div class="col-sm-4 form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username" placeholder="Username" required="required">
                </div>
                <div class="col-sm-4 form-group">
                    <label for="fromDatePicker">Start Datum</label>
                    <div id="fromDatePicker">
                        <input type="hidden" name="fromDate" data-validate="true" required="required">
                    </div>
                </div>
                <div class="col-sm-4 form-group">
                    <label for="toDatePicker">End Datum</label>
                    <div id="toDatePicker">
                        <input type="hidden" name="toDate" data-validate="true" required="required">
                    </div>
                </div>
                <div class="col-xs-12 form-group">
                    <button type="submit" class="btn btn-primary">anzeigen</button>
                </div>
            </form>
        </div>
    </div>
<?php include('partials/footer.phtml'); ?>

