<?php
include('partials/header.phtml');

function showdaysLabel($label) {
    if($label<10) {
        return $label;
    }
    if($label<36) {
        return chr($label-10+ord('A'));
    }
    return '-';
}

?>

    <div class="container">

        <div class="row">
            <div class="col-xs-12">
                <h2>Übersicht für <a href="https://www.geocaching.com/p/default.aspx?guid=<?= $user['PublicGuid'] ?>" target="_blank"><?= $user['UserName'] ?></a> vom <?= $input['from'] ?> bis <?= $input['to'] ?></h2>
            </div>
            <div class="col-lg-4 col-sm-6 col-xs-12">
                <?php $premium = $user['MemberType']['MemberTypeId']==3 ? ' <img src="/assets/images/premium.png" alt="Premium Member" title="Premium Member" />' : ''; ?>
                <table>
                    <tr>
                        <td style="padding-right: 10px"><img src="<?= $user['AvatarUrl'] ?>" /></td>
                        <td valign="top">
                            <a href="https://www.geocaching.com/p/default.aspx?guid=<?= $user['PublicGuid'] ?>" target="_blank"><?= $user['UserName'].$premium ?></a><br />
                            Versteckt: <?= $user['HideCount'] ?><br />
                            Gefunden: <?= $user['FindCount'] ?>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-lg-4 col-sm-6 col-xs-12">
                <table class="table table-striped table-condensed">
                    <thead>
                        <tr>
                            <th>Datum</th>
                            <th>Logs</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach($logs as $day => $cacheCodes): ?>
                        <?php $dayDate = new DateTime($day); ?>
                        <tr>
                            <td><a href="#day-<?= $day ?>"><?= $dayDate->format('d.m.Y'); ?></a></td>
                            <td><?= count($cacheCodes) ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <h2>Tagestouren</h2>
                <table class="table table-condensed" id="table-showdays">
                    <tbody>
                        <?php foreach($logs as $day => $cacheCodes): ?>
                            <?php
                                // Create minimap url (google static map)
                                $minimapBaseParameters = [
                                    'format' => 'png',
                                    'maptype' => 'terrain',
                                    'key' => $config['googleApiToken'],
                                ];
                                $minimapMarkerParameters = [];
                                $label = 1;
                                foreach($cacheCodes as $cacheCode) {
                                    $labelString = showdaysLabel($label)!=='-' ? 'label:'.showdaysLabel($label) : '';
                                    $minimapMarkerParameters[] = 'markers=size:mid|color:red|'.$labelString.'|'.$caches[$cacheCode]['Latitude'].','.$caches[$cacheCode]['Longitude'];
                                    $label++;
                                }
                                $minimapBaseUrl = 'https://maps.googleapis.com/maps/api/staticmap?';
                                $minimapBaseUrl.= http_build_query($minimapBaseParameters);
                                $minimapBaseUrl.= '&'.implode('&', $minimapMarkerParameters);
                                $minimapSmallUrl = $minimapBaseUrl.'&size=240x240';
                                $minimapLargeUrl = str_replace('size:mid|', '', $minimapBaseUrl).'&size=640x640';
                                // formattable date
                                $dayDate = new DateTime($day);
                            ?>
                            <tr>
                                <td colspan="3">
                                    <h3><a id="day-<?= $day ?>" class="link-unstyled"><?= $dayDate->format('d.m.Y') ?></a> (<?= count($cacheCodes) ?>)</h3>
                                </td>
                                <td colspan="7">
                                    <div class="hidden-lg">
                                        <button type="button" class="btn btn-primary pull-right button-align-h3" data-toggle="modal" data-target=".minimap-<?= $day ?>">Map</button>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <th>#</th>
                                <th>Code</th>
                                <th>Name</th>
                                <th>Container</th>
                                <th>Difficulty</th>
                                <th>Terrain</th>
                                <th>Owner</th>
                                <th>Favo</th>
                                <th>Tools</th>
                                <th class="visible-lg">Map</th>
                            </tr>
                            <?php $i = 1; ?>
                            <?php foreach($cacheCodes as $cacheCode): ?>
                                <?php $cache = $caches[$cacheCode]; ?>
                                <?php $trExtraClass = $i==count($cacheCodes) ? 'last' : 'notlast' ?>
                                <tr class="<?= $trExtraClass ?>">
                                    <td><?= showdaysLabel($i) ?></td>
                                    <td>
                                        <a href="<?= $cache['Url']?>" target="_blank"><?= $cache['Code'] ?></a>
                                        <?php if($i==1): ?>
                                            <div class="modal fade minimap-<?= $day ?>" tabindex="-1" role="dialog">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                            <h4 class="modal-title"><?= $user['UserName'] ?> / <?= $dayDate->format('d.m.Y') ?></h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <img class="img-responsive" src="<?= $minimapLargeUrl ?>">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </td>
                                    <td>
                                        <img src="<?= $cache['CacheType']['ImageURL'] ?>" alt="<?= $cache['CacheType']['GeocacheTypeName'] ?>" height="16">
                                        <?= $cache['Name'] ?>
                                    </td>
                                    <td><div class="nowrap"><img src="https://www.geocaching.com/images/icons/container/<?= str_replace(' ', '_', $cache['ContainerType']['ContainerTypeName'])?>.gif" /> <?= $cache['ContainerType']['ContainerTypeName'] ?></div></td>
                                    <td><img src="https://www.geocaching.com/images/stars/stars<?= str_replace('.', '_', $cache['Difficulty']) ?>.gif" /></td>
                                    <td><img src="https://www.geocaching.com/images/stars/stars<?= str_replace('.', '_', $cache['Terrain']) ?>.gif" /></td>
                                    <td><div class="nowrap"><a href="https://www.geocaching.com/p/default.aspx?guid=<?= $cache['Owner']['PublicGuid'] ?>" target="_blank"><?= $cache['Owner']['UserName'] ?></a></div></td>
                                    <td><div class="nowrap"><img src="/assets/images/favorite.png" alt="Favorites" title="Favorites" /> <?= $cache['FavoritePoints'] ?></div></td>
                                    <td>
                                        <a href="http://gc-analyzer.frigidor.ch/<?= $cache['Code'] ?>" target="_blank"><img src="/assets/images/gc-analyzer.png" alt="GC Analyzer" title="GC Analyzer" /></a>
                                    </td>
                                    <?php if($i==1): ?>
                                        <td class="visible-lg" rowspan="<?= count($cacheCodes) ?>">
                                            <a href="#" data-toggle="modal" data-target=".minimap-<?= $day ?>"><img src="<?= $minimapSmallUrl ?>" width="240" height="240"></a>
                                        </td>
                                    <?php endif; ?>
                                </tr>
                                <?php $i++ ?>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>

    </div>

<?php include('partials/footer.phtml'); ?>

